### ISSUE TITLE
Docker container persistent config/announcements

### ISSUE THREAD

**Issue by SanderDelden** [Exa-Networks/exabgp#1095]
I'm using Quagga as a BGP instance for use with Wanguard. Wanguard announces routes to ExaBGP using the pipe which all works fine. However when restarting the ExaBGP container the previously inserted announcements are no longer presented which can lead to some issues for us.

The configuration looks as follows:

Dockerfile:
```
FROM python:3.9.12-slim-buster

ARG EXABGP_VERSION

# update and install packages
RUN apt update && \
    apt install -y \
        dumb-init && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# add exabgp
ADD https://github.com/Exa-Networks/exabgp/archive/refs/tags/${EXABGP_VERSION}.tar.gz /tmp
RUN mkdir /etc/exabgp && \
    tar -xzf /tmp/${EXABGP_VERSION}.tar.gz --strip-components=1 -C /etc/exabgp && \
    rm /tmp/${EXABGP_VERSION}.tar.gz

# copy healthcheck & entrypoint script
COPY $PWD/docker/exabgp/docker-healthcheck.sh $PWD/docker/exabgp/docker-entrypoint.sh /

ENTRYPOINT [ "dumb-init", "--" ]
CMD [ "./docker-entrypoint.sh" ]
```

Entrypoint:
```
#!/bin/bash

set -euo pipefail

PIPE_PATH=/run/exabgp/
IN_PIPE=exabgp.in
OUT_PIPE=exabgp.out

# check if exabgp pipe exists, if not add it
if [ ! -d "$PIPE_PATH" ]; then
  mkdir -p "$PIPE_PATH"
  chown nobody "$PIPE_PATH"
fi
if [ ! -p "${PIPE_PATH}${IN_PIPE}" ]; then
  mkfifo "${PIPE_PATH}${IN_PIPE}"
  chown nobody "${PIPE_PATH}${IN_PIPE}"
  chmod 600 "${PIPE_PATH}${IN_PIPE}"
fi
if [ ! -p "${PIPE_PATH}${OUT_PIPE}" ]; then
  mkfifo "${PIPE_PATH}${OUT_PIPE}"
  chown nobody "${PIPE_PATH}${OUT_PIPE}"
  chmod 600 "${PIPE_PATH}${OUT_PIPE}"
fi

# start exabgp
/etc/exabgp/sbin/exabgp /var/lib/exabgp/exabgp.conf
```

ExaBGP config file:
```
# default template

template {
    neighbor neighbor_group {
	    router-id 172.20.0.20;
	    local-address 172.20.0.20;
	    local-as 12345;
	    peer-as 12345;
	    hold-time 180;
    }
}

# mock core routers

neighbor 172.20.0.21 {
    inherit neighbor_group;
	description "quagga-router1-mock";
}
neighbor 172.20.0.22 {
    inherit neighbor_group;
	description "quagga-router2-mock";
}
```

Compose file:
```
  exabgp:
    image: ${COMPOSE_PROJECT_NAME}/${EXABGP_DOCKER_IMAGE_NAME}:${EXABGP_VERSION}
    restart: unless-stopped
    networks:
      wanguard_network:
        ipv4_address: ${EXABGP_IP_ADDRESS}
    environment:
      EXABGP_VERSION: ${EXABGP_VERSION}
      TZ: Europe/Amsterdam
    healthcheck:
      test: [CMD, bash, /docker-healthcheck.sh]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
    - $PWD/exabgp/exabgp.conf:/var/lib/exabgp/exabgp.conf:ro
    - exabgp_data:/etc/exabgp
    - exabgp_shared:/run/exabgp

volumes:
  exabgp_data:
  exabgp_shared:
```

Any help on this would be greatly appreciated!
